server:
  port: 8070
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5